# Generated by Django 4.2.7 on 2024-02-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_song_song_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="song_url",
        ),
        migrations.AddField(
            model_name="song",
            name="local_file_path",
            field=models.FileField(default="", upload_to="song/"),
        ),
    ]
