# Generated by Django 4.2.7 on 2024-02-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_song_local_file_path_song_local_music_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="local_music_file",
            field=models.FileField(default="", upload_to="accounts/media"),
        ),
    ]
