# Generated by Django 4.2.7 on 2024-02-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_remove_song_local_music_file_song_audio_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="audio_file",
            field=models.FileField(default="Aliah Final.mp3", upload_to="songs/"),
        ),
    ]
