# Generated by Django 4.2.7 on 2024-02-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_alter_song_audio_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="audio_file",
            field=models.FileField(
                default="2.mp3", upload_to="mywebsite/accounts/media/songs/"
            ),
        ),
    ]
