# Generated by Django 4.2.7 on 2024-02-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_alter_song_audio_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="audio_file",
        ),
        migrations.AddField(
            model_name="song",
            name="youtube_url",
            field=models.URLField(
                default="https://www.youtube.com/watch?v=jzQvggUparA"
            ),
        ),
    ]
