# Generated by Django 4.2.7 on 2024-02-11 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_remove_song_audio_file_song_youtube_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="album",
        ),
        migrations.RemoveField(
            model_name="song",
            name="youtube_url",
        ),
        migrations.AddField(
            model_name="song",
            name="artist",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.artist",
            ),
        ),
        migrations.DeleteModel(
            name="Album",
        ),
    ]
