# Generated by Django 4.2.7 on 2024-02-11 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_remove_concert_artist_concert_artists_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concert",
            name="artists",
            field=models.ManyToManyField(related_name="concerts", to="accounts.artist"),
        ),
        migrations.AlterField(
            model_name="song",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="songs",
                to="accounts.artist",
            ),
        ),
        migrations.DeleteModel(
            name="Booking",
        ),
    ]
