# Generated by Django 4.2.7 on 2024-02-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_alter_concert_artists_alter_song_artist_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="description",
            field=models.CharField(default="No description provided.", max_length=200),
        ),
    ]
